version: '3.8'

services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: "amarelo123"
      MYSQL_DATABASE: "clients"
      MYSQL_PASSWORD: "amarelo123"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
